name: Combine Geode mods
description: Combines the same Geode mod built for different platforms into a single file

inputs:
  cli:
    description: Which CLI version to use, defaults to latest release.
    required: false
    default: latest
  delete-artifacts:
    description: Whether to delete temporary artifacts left by the build action.
    required: false
    default: true

outputs:
  build-output:
    description: A folder containing the built .geode file(s)
    value: ${{ steps.merge.outputs.output }}

runs:
  using: composite
  steps:
    - name: Detect platform
      id: platform
      shell: bash
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          ID=linux
        elif [ "$RUNNER_OS" = "Windows" ]; then
          ID=win
        elif [ "$RUNNER_OS" = "macOS" ]; then
          ID=mac
        fi
        echo "id=$ID" >> $GITHUB_OUTPUT

    - name: Download CLI
      uses: robinraju/release-downloader@v1.9
      with:
        repository: geode-sdk/cli
        latest: ${{ inputs.cli == 'latest' }}
        tag: ${{ inputs.cli != 'latest' && inputs.cli || '' }}
        fileName: "*-${{ steps.platform.outputs.id }}.zip"
        tarBall: false
        zipBall: false
        out-file-path: "cli"

    - name: Setup CLI
      shell: bash
      run: |
        7z x "cli/*-${{ steps.platform.outputs.id }}.zip" -ocli
        echo "${{ github.workspace }}/cli" >> $GITHUB_PATH

        if [ ${{ steps.platform.outputs.id }} != "win" ]; then
          chmod +x "cli/geode"
        fi

    - uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Combine them
      shell: bash
      id: merge
      run: |
        chmod +x ./geode
        mkdir out
        MODS=$(find . -name *.geode -type f -printf "%f\n" | sort -u)
        for mod in $MODS; do
          PACKAGE_ARGS=""
          if [ -f "./artifacts/geode-build-win/$mod" ]; then
            PACKAGE_ARGS="$PACKAGE_ARGS ./artifacts/geode-build-win/$mod"
          fi
          if [ -f "./artifacts/geode-build-mac/$mod" ]; then
            PACKAGE_ARGS="$PACKAGE_ARGS ./artifacts/geode-build-mac/$mod"
          fi
          if [ -f "./artifacts/geode-build-android32/$mod" ]; then
            PACKAGE_ARGS="$PACKAGE_ARGS ./artifacts/geode-build-android32/$mod"
          fi
          if [ -f "./artifacts/geode-build-android64/$mod" ]; then
            PACKAGE_ARGS="$PACKAGE_ARGS ./artifacts/geode-build-android64/$mod"
          fi
          ARG_LIST=($PACKAGE_ARGS)
          # why does it merge into the first one instead of just an output..
          FIRST="${ARG_LIST[0]}"
          if [ ${#ARG_LIST[@]} != 1 ]; then
            geode package merge $PACKAGE_ARGS
          fi
          cp $FIRST out
        done
        echo "output=${{ github.workspace }}/out" >> $GITHUB_OUTPUT

    - uses: geekyeggo/delete-artifact@v4
      if: ${{ inputs.delete-artifacts }}
      with:
          name: geode-build-win
          failOnError: false
        
    - uses: geekyeggo/delete-artifact@v4
      if: ${{ inputs.delete-artifacts }}
      with:
          name: geode-build-mac
          failOnError: false

    - uses: geekyeggo/delete-artifact@v4
      if: ${{ inputs.delete-artifacts }}
      with:
          name: geode-build-android32
          failOnError: false

    - uses: geekyeggo/delete-artifact@v4
      if: ${{ inputs.delete-artifacts }}
      with:
          name: geode-build-android64
          failOnError: false